# Site settings
title: Qgon
baseurl: ""
url: "http://www.qgon.nl"
timezone: "Europe/Amsterdam"

# Exclude
exclude:
  - CNAME

# Plugins
plugins: ["jekyll-paginate"]

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"

# Google
google:
  analytics:
    tracking-id: UA-148590782-1
  maps:
    api-key: AIzaSyCztmPOJhwXX9FWJOOFhpiKaSCYlYYJybw
